### ISSUE TITLE
Filtering by Site with the "get-inventory" command doesn't work correctly

### ISSUE THREAD

**Issue by matt852** [nautobot/nautobot-plugin-chatops-ipfabric#105]
### Environment
* Python version:    Unknown
* Nautobot version:  . 1.2.8
* ipfabric version:   1.1.1

### Expected Behavior
When running the command `/ipfabric get-inventory`, and selecting `Sites` from the Filter dropdown, a list of existing sites should appear in the following dropdown.

### Observed Behavior
Instead, a list of devices appears in the dropdown.  The other 3 Filter options work correctly (Vendor, Platform, and Model).

### Steps to Reproduce
1. Run command `/ipfabric get-inventory`
2. Select `Sites` from the first "Filter inventory by" prompt
3. Observe presented options in second, more specific "Filter by" dropdown

**Comment by pke11y** [comment]
Hi @matt852 , thanks for the issue. Can you ping me on Slack with the URL for the dataset you're using please? 
It's working for me.

**Comment by pauljorgenson** [comment]
@pke11y and @matt852 I can take a look. Do we have a URL for the dataset that was used?

**Comment by pauljorgenson** [comment]
This is not an issue with the ipfabric chatops plugin but rather with the source data. The site names used in the instance were the device names but in all caps, which made it look like the plugin had an issue showing the wrong data.

This issue can be closed.
