### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-plugin-chatops-ipfabric#55]
### Environment

pypi

### Expected Behavior

Package to be published

### Observed Behavior

Not in pypi

### Steps to Reproduce
1. Navigate to pypi.org
2. Search ipfabric
3. This is not found

**Comment by sdargoeuves** [comment]
Thank you for raising it, I was going to test this morning. As I'm not sure how to proceed with manual installation, I'll wait until this is published!

**Comment by pke11y** [comment]
Resolved with #56
