### ISSUE TITLE
Add SSL Verification environment variable

### ISSUE THREAD

**Issue by justinjeffery-ipf** [nautobot/nautobot-plugin-chatops-ipfabric#64]
### Environment
* Nautobot version:  
* ipfabric version:  4.2

Cannot connect to self-signed IP Fabric instances
### Proposed Functionality

Environment variable IPF_VERIFY
### Use Case
 Example error:
HTTPSConnectionPool(host='demo3.ipf.ipfabric.io', port=443): Max retries exceeded with url: /api/v1/tables/addressing/hosts (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))* :warning:

**Comment by justinjeffery-ipf** [comment]
PR #65

**Comment by pke11y** [comment]
Resolved with #65
