### ISSUE TITLE
Teams Images Does not work

### ISSUE THREAD

**Issue by justinjeffery-ipf** [nautobot/nautobot-plugin-chatops-ipfabric#81]
### Environment
* Python version:  3.9
* Nautobot version:  1.2.4
* ipfabric version:  1.1.0

### Expected Behavior
Image should be sent to Teams.

Need to ask permission before trying to send.
https://github.com/nautobot/nautobot-plugin-chatops/blob/da60e9594e29380a39dbab54679da9a8c39fbec2/nautobot_chatops/dispatchers/ms_teams.py#L119

### Observed Behavior
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nautobot_chatops_ipfabric/worker.py", line 530, in pathlookup
    dispatcher.send_image(img_path)
  File "/usr/local/lib/python3.9/site-packages/nautobot_chatops/dispatchers/ms_teams.py", line 180, in send_image
    raise RuntimeError("send_image() called without permission being granted to send an image")
RuntimeError: send_image() called without permission being granted to send an image

### Steps to Reproduce
1.
2.
3.

**Comment by smk4664** [comment]
I can take this issue.  For MS Teams, we need to ask for permission before sending the issue.
